根据enableEditing配置来判定完成绘制后是否需要编辑
huiyan-fe/BMapGLLib pull request #38
Opened 2022-06-24 08:51 UTC by freeeeeedom

根据enableEditing配置来判定完成绘制后是否需要编辑

2022-06-29 12:03 UTC, Junior2Ran requested changes

2022-07-04 10:54 UTC, freeeeeedom commented
修改方法名为_skipEditing更贴合实际用途
修改参数名为skipEditing更贴合实际用途
排除可能的undefined问题
@Junior2Ran

2022-07-07 03:54 UTC, freeeeeedom commented
合并了模拟点击条件判定
* 默认场景 不配参数 不模拟点击
* 普通场景 任一为true模拟点击完成
* 特殊场景 masterSkipEditing=true optionsSkipEditing=false 不模拟点击
@Junior2Ran

2022-07-07 07:43 UTC, Junior2Ran approved these changes

2022-07-07 07:43 UTC, merged